import re

# Mapa fonetico: sustituir nombres antes de enviar al TTS en espanol
# Permite que AlvaroNeural pronuncie los nombres ingleses correctamente
PHONETIC_MAP = {
    # Informatica / Tecnologia
    "Lovelace":    "Lavleis",
    "Turing":      "Tiuring",
    "Hopper":      "Joper",
    "Hamilton":    "Jamilton",
    "Katherine":   "Katerine",
    "Lamarr":      "Lamar",
    "Hedy":        "Jedi",
    "Berners-Lee": "Berners Li",
    "Berners":     "Berners",
    "Vint":        "Bint",
    "Cerf":        "Serf",
    "Kahn":        "Kan",
    "Shannon":     "Shanon",
    "Dennis":      "Denis",
    "Ritchie":     "Richi",
    "Thompson":    "Tompson",
    "Linus":       "Lainus",
    "Torvalds":    "Torvalds",
    "Stallman":    "Stolman",
    "Rossum":      "Rosum",
    "Knuth":       "Nuth",
    "Radia":       "Reidia",
    "Perlman":     "Perlman",
    "Liskov":      "Liscov",
    "Sophie":      "Sofi",
    "Wilson":      "Uilson",
    "Douglas":     "Duglas",
    "Engelbart":   "Engelbart",
    "Kare":        "Ker",
    "Steve":       "Estiv",
    "Jobs":        "Yobs",
    "Wozniak":     "Uozniak",
    "Gates":       "Gueis",
    "Edison":      "Edison",
    "Graham":      "Greiam",
    # Ciencia
    "Einstein":    "Ainshtain",
    "Newton":      "Niuton",
    "Isaac":       "Aizak",
    "Watson":      "Uotson",
    "James":       "Yeims",
    "Crick":       "Crik",
    "Jennifer":    "Yenifer",
    "Doudna":      "Dudna",
    "Weissman":    "Uaisman",
    "Drew":        "Dru",
    "Salk":        "Solk",
    "Jonas":       "Yonas",
    "Fleming":     "Fleming",
    "Nightingale": "Naitingueil",
    "Florence":    "Florens",
    "Semmelweis":  "Semelveis",
    "Jenner":      "Yener",
    "Goodall":     "Gudol",
    "Jane":        "Yein",
    "Rachel":      "Reichel",
    "Carson":      "Karson",
    "Maathai":     "Matai",
    "Earle":       "Erl",
    "Cousteau":    "Custo",
    "Jacques":     "Yak",
    "Earhart":     "Erjart",
    "Amelia":      "Emelia",
    "Jemison":     "Yemison",
    "Mae":         "Mei",
    "Sally":       "Sali",
    "Ride":        "Raid",
    "Dorothy":     "Doroti",
    "Vaughan":     "Von",
    "Meitner":     "Maitner",
    "Leavitt":     "Livit",
    "Henrietta":   "Jentrieta",
    # Arte / Literatura
    "Shelley":     "Sheli",
    "George":      "Yory",
    "Orwell":      "Oruel",
    "Virginia":    "Virchinia",
    "Woolf":       "Wulf",
    "Vincent":     "Binsent",
    "Beethoven":   "Beitoven",
    "Ludwig":      "Ludvig",
    "Wolfgang":    "Volfgang",
    "Mozart":      "Motsart",
    "Dylan":       "Dailan",
    "Angelou":     "Anyelu",
    # Activistas / Humanitarios
    "Claudette":   "Clodet",
    "Colvin":      "Kolvin",
    "Harriet":     "Yariet",
    "Tubman":      "Tubman",
    "Schindler":   "Shindler",
    "Winton":      "Uinton",
    "Temple":      "Templ",
    "Grandin":     "Grendin",
    "Borlaug":     "Borlog",
    "Boyan":       "Boian",
    "Muhammad":    "Mohamed",
    "Wright":      "Rait",
    # Nombres frecuentes en ingles
    "Mary":        "Meri",
    "Dorothy":     "Doroti",
    "Jackson":     "Yakson",
    "Thomas":      "Tomas",
    "Allen":       "Alen",
}


def apply_phonetics(text: str) -> str:
    # Sustituir compuestos primero (orden de mayor a menor longitud)
    for original, phonetic in sorted(PHONETIC_MAP.items(), key=lambda x: -len(x[0])):
        text = re.sub(r'\b' + re.escape(original) + r'\b', phonetic, text, flags=re.IGNORECASE)
    return text
